<?php


namespace App\Views\Components;

class SceneDirector
{
    /**
     * Generates a card with a title and an image
     *
     * @param string $title      The title of the content
     * @param string $imageUrl   The URL of the image that serves as the content poster
     * @return void
     */
    private function generateStandardPosterCard(string $title, string $imageUrl): void
    {
        echo '
        <a href="" class="card-poster">
            <div class="image-container">
            <img class="thumbnail" src="' . $imageUrl . '" class="blurred-image">
            <div class="overlay-text">
                <p>' . $title . '</p>
            </div>
            </div>
        </a>
        ';
    }
    /**
     * Organizes the cards generated by the generateStandardPosterCard method
     *
     * @param array $contents   Contains information about the contents
     * @param int $rowSize      Specifies the number of cards to display per row, defaults to 3
     * @return void
     */
    public function generateStandardPosters(array $contents, int $rowSize = 3): void
    {
        $i = 0;
        foreach ($contents as $content) {
            if ($i === 0) {
                echo '<div class="row">';
            }

            $this->generateStandardPosterCard($content['title'], $content['image_url']);

            if ($i === $rowSize - 1) {
                echo '</div>';
                $i = -1;
            }
            $i++;
        }
    }
}